#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export DIST_PATH=${DIR}
export ANBN_KI_OS_PATH=$(<${DIR}/anbnkios_path)
export PATH=$PATH:$ANBN_KI_OS_PATH

${ANBN_KI_OS_PATH}/build_custom_os $@
