#!/usr/bin/env bash
# anbnkiOS auto-mount-removable media module
# Script sets that devices would be automatically mounted to /media
# Written by Guy Sheffer and updated by Esan Maruff <bmaruff gmail dot com>
# GPL V3
########
set -x
set -e

source /common.sh

apt-get update --allow-releaseinfo-change
apt-get install -y usbmount

unpack /filesystem/root /
